#!/data/data/com.termux/files/usr/bin/bash

function build_resynthesizer() {
    print_msg "Building Resynthesizer..."
    package_install_and_check "cmake ninja xorgproto python3"
    pip install meson
    git clone --recursive --depth=1 -j "$(nproc)" https://github.com/bootchk/resynthesizer.git -b resynthesizer3
    cd resynthesizer || exit 1
    meson setup builddir --prefix="$PREFIX"
    ninja -C builddir
    ninja -C builddir install
}

function call_build() {
    local attempt
    attempt=1
    local max_retries
    max_retries=2
    while [[ "$attempt" -le "$max_retries" ]]; do
        build_resynthesizer
        if [[ -d "/data/data/com.termux/files/usr/lib/gimp/3.0/plug-ins/resynthesizer" ]]; then
            print_success "Resynthesizer install successfully"
            break
        else
            print_failed "Resynthesizer build failed, Retrying..."
            meson --wipe builddir
            ((attempt++))
        fi
    done
}

call_build
