#!/data/data/com.termux/files/usr/bin/bash
#
# Termux Color Scheme Switcher
# A TUI tool to switch between color schemes with live preview.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Author     : @sabamdarif
# License    : GPL-v3
# Description: Simple terminal UI tool for managing Termux color schemes.
# Part of    : sabamdarif/termux-desktop
# Repository : https://github.com/sabamdarif/termux-desktop

COLORS_FILE="$HOME/.termux/colors.properties"
BACKUP_FILE="$HOME/.termux/colors.properties.backup.$(date +%Y%m%d_%H%M%S)"

# Create backup of current colors
backup_colors() {
    if [[ -f "$COLORS_FILE" ]]; then
        cp "$COLORS_FILE" "$BACKUP_FILE"
    fi
}

# Restore backup colors
restore_colors() {
    if [[ -f "$BACKUP_FILE" ]]; then
        cp "$BACKUP_FILE" "$COLORS_FILE"
        termux-reload-settings
        rm "$BACKUP_FILE"
    fi
}

# Apply color scheme
apply_colors() {
    local scheme_name="$1"

    case "$scheme_name" in
    "Catppuccin Macchiato")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/catppuccin/termux/blob/main/themes/catppuccin-macchiato.properties
background:     #24273a
foreground:     #cad3f5
color0:         #494d64
color8:         #5b6078
color1:         #ed8796
color9:         #ed8796
color2:         #a6da95
color10:        #a6da95
color3:         #eed49f
color11:        #eed49f
color4:         #8aadf4
color12:        #8aadf4
color5:         #f5bde6
color13:        #f5bde6
color6:         #8bd5ca
color14:        #8bd5ca
color7:         #b8c0e0
color15:        #a5adcb
EOF
        ;;
    "Catppuccin Mocha")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/catppuccin/termux/blob/main/themes/catppuccin-mocha.properties
background:     #24273a
foreground:     #cad3f5
color0:         #494d64
color8:         #5b6078
color1:         #ed8796
color9:         #ed8796
color2:         #a6da95
color10:        #a6da95
color3:         #eed49f
color11:        #eed49f
color4:         #8aadf4
color12:        #8aadf4
color5:         #f5bde6
color13:        #f5bde6
color6:         #8bd5ca
color14:        #8bd5ca
color7:         #b8c0e0
color15:        #a5adcb
EOF
        ;;
    "Catppuccin Latte")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/catppuccin/termux/blob/main/themes/catppuccin-latte.properties
background:     #eff1f5
foreground:     #4c4f69
color0:         #5c5f77
color8:         #acb0be
color1:         #d20f39
color9:         #d20f39
color2:         #40a02b
color10:        #40a02b
color3:         #df8e1d
color11:        #df8e1d
color4:         #1e66f5
color12:        #1e66f5
color5:         #ea76cb
color13:        #ea76cb
color6:         #179299
color14:        #179299
color7:         #acb0be
color15:        #bcc0cc
EOF
        ;;
    "Catppuccin Frappe")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/catppuccin/termux/blob/main/themes/catppuccin-frappe..properties
background:     #303446
foreground:     #c6d0f5
color0:         #51576d
color8:         #626880
color1:         #e78284
color9:         #e78284
color2:         #a6d189
color10:        #a6d189
color3:         #e5c890
color11:        #e5c890
color4:         #8caaee
color12:        #8caaee
color5:         #f4b8e4
color13:        #f4b8e4
color6:         #81c8be
color14:        #81c8be
color7:         #b5bfe2
color15:        #a5adce
EOF
        ;;

    "Dracula")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/dracula/termux/blob/master/colors.properties
background:     #282A36
foreground:     #F8F8F2
color0:         #000000
color8:         #4D4D4D
color1:         #FF5555
color9:         #FF6E67
color2:         #50FA7B
color10:        #5AF78E
color3:         #F1FA8C
color11:        #F4F99D
color4:         #BD93F9
color12:        #CAA9FA
color5:         #FF79C6
color13:        #FF92D0
color6:         #8BE9FD
color14:        #9AEDFE
color7:         #BFBFBF
color15:        #E6E6E6
EOF
        ;;
    "Gruvbox Dark")
        cat >"$COLORS_FILE" <<'EOF'
# Gruvbox Dark
background:     #282828
foreground:     #ebdbb2
color0:         #282828
color8:         #928374
color1:         #cc241d
color9:         #fb4934
color2:         #98971a
color10:        #b8bb26
color3:         #d79921
color11:        #fabd2f
color4:         #458588
color12:        #83a598
color5:         #b16286
color13:        #d3869b
color6:         #689d6a
color14:        #8ec07c
color7:         #a89984
color15:        #ebdbb2
EOF
        ;;
    "Nord")
        cat >"$COLORS_FILE" <<'EOF'
# Nord
background:     #2e3440
foreground:     #d8dee9
color0:         #3b4252
color8:         #4c566a
color1:         #bf616a
color9:         #bf616a
color2:         #a3be8c
color10:        #a3be8c
color3:         #ebcb8b
color11:        #ebcb8b
color4:         #81a1c1
color12:        #81a1c1
color5:         #b48ead
color13:        #b48ead
color6:         #88c0d0
color14:        #8fbcbb
color7:         #e5e9f0
color15:        #eceff4
EOF
        ;;
    "One Dark")
        cat >"$COLORS_FILE" <<'EOF'
# One Dark
background:     #282c34
foreground:     #abb2bf
color0:         #282c34
color8:         #545862
color1:         #e06c75
color9:         #e06c75
color2:         #98c379
color10:        #98c379
color3:         #e5c07b
color11:        #e5c07b
color4:         #61afef
color12:        #61afef
color5:         #c678dd
color13:        #c678dd
color6:         #56b6c2
color14:        #56b6c2
color7:         #abb2bf
color15:        #c8ccd4
EOF
        ;;
    "Solarized Dark")
        cat >"$COLORS_FILE" <<'EOF'
# Solarized Dark
background:     #002b36
foreground:     #839496
color0:         #073642
color8:         #002b36
color1:         #dc322f
color9:         #cb4b16
color2:         #859900
color10:        #586e75
color3:         #b58900
color11:        #657b83
color4:         #268bd2
color12:        #839496
color5:         #d33682
color13:        #6c71c4
color6:         #2aa198
color14:        #93a1a1
color7:         #eee8d5
color15:        #fdf6e3
EOF
        ;;
    "Tokyo Night")
        cat >"$COLORS_FILE" <<'EOF'
# Tokyo Night
background:     #1a1b26
foreground:     #c0caf5
color0:         #15161e
color8:         #414868
color1:         #f7768e
color9:         #f7768e
color2:         #9ece6a
color10:        #9ece6a
color3:         #e0af68
color11:        #e0af68
color4:         #7aa2f7
color12:        #7aa2f7
color5:         #bb9af7
color13:        #bb9af7
color6:         #7dcfff
color14:        #7dcfff
color7:         #a9b1d6
color15:        #c0caf5
EOF
        ;;
    "Monokai")
        cat >"$COLORS_FILE" <<'EOF'
# Monokai
background:     #272822
foreground:     #f8f8f2
color0:         #272822
color8:         #75715e
color1:         #f92672
color9:         #f92672
color2:         #a6e22e
color10:        #a6e22e
color3:         #f4bf75
color11:        #f4bf75
color4:         #66d9ef
color12:        #66d9ef
color5:         #ae81ff
color13:        #ae81ff
color6:         #a1efe4
color14:        #a1efe4
color7:         #f8f8f2
color15:        #f9f8f5
EOF
        ;;
    "Oceanic Next")
        cat >"$COLORS_FILE" <<'EOF'
# Oceanic Next
background:     #1b2b34
foreground:     #d8dee9
color0:         #29414f
color8:         #405860
color1:         #ec5f67
color9:         #ec5f67
color2:         #99c794
color10:        #99c794
color3:         #fac863
color11:        #fac863
color4:         #6699cc
color12:        #6699cc
color5:         #c594c5
color13:        #c594c5
color6:         #5fb3b3
color14:        #5fb3b3
color7:         #d8dee9
color15:        #d8dee9
EOF
        ;;
    "Ubuntu")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/Mayccoll/Gogh/blob/master/themes/clone-of-ubuntu.sh
background=#300a24
foreground=#ffffff
cursor=#ffffff
color0=#2E3436
color1=#CC0000
color2=#4E9A06
color3=#C4A000
color4=#3465A4
color5=#75507B
color6=#06989A
color7=#D3D7CF
color8=#555753
color9=#EF2929
color10=#8AE234
color11=#FCE94F
color12=#729FCF
color13=#AD7FA8
color14=#34E2E2
color15=#EEEEEC
EOF
        ;;
    "E-link Color")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/termux/termux-styling/blob/master/app/src/main/assets/colors/e-ink-color.properties
background=#ffffff
foreground=#000000
cursor=#c0c0c0

color0=#000000
color1=#800000
color2=#008000
color3=#808000
color4=#000080
color5=#800080
color6=#008080
color7=#c0c0c0

color8=#808080
color9=#ff0000
color10=#00ff00
color11=#ffff00
color12=#0000ff
color13=#ff00ff
color14=#00ffff
color15=#ffffff
EOF
        ;;
    "E-link")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/termux/termux-styling/blob/master/app/src/main/assets/colors/e-ink.properties
background: #FFFFFF
foreground: #000000
cursor=#c0c0c0

color0=#101010
color1=#7c7c7c
color2=#8e8e8e
color3=#a0a0a0
color4=#686868
color5=#747474
color6=#868686
color7=#b9b9b9
color8=#525252
color9=#7c7c7c
color10=#8e8e8e
color11=#a0a0a0
color12=#686868
color13=#747474
color14=#868686
color15=#f7f7f7
EOF
        ;;
    "Ayu Dark")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/ayu-dark.colors
background=#090D13
foreground=#FEFEFE
cursor=#E96B72
color0=#00050D
color1=#E96B72
color2=#90B261
color3=#F8AE4E
color4=#52BCF9
color5=#F9E893
color6=#8FE0C5
color7=#C6C6C6
color8=#676767
color9=#EF7077
color10=#C1D84B
color11=#FEB353
color12=#58C1FE
color13=#FEED98
color14=#94E5CA
color15=#FEFEFE
EOF
        ;;

    "Ayu Light")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/ayu-light.colors

background=#FEFEFE
foreground=#090D13
cursor=#E96B72
color0=#00050D
color1=#E96B72
color2=#90B261
color3=#F8AE4E
color4=#52BCF9
color5=#F9E893
color6=#8FE0C5
color7=#C6C6C6
color8=#676767
color9=#EF7077
color10=#C1D84B
color11=#FEB353
color12=#58C1FE
color13=#FEED98
color14=#94E5CA
color15=#FEFEFE
EOF
        ;;
    "Ayu Mirage")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/ayu-mirage.colors

background=#1F2430
foreground=#E5E0CE
cursor=#E96B72
color0=#00050D
color1=#E96B72
color2=#90B261
color3=#F8AE4E
color4=#52BCF9
color5=#F9E893
color6=#8FE0C5
color7=#C6C6C6
color8=#676767
color9=#EF7077
color10=#C1D84B
color11=#FEB353
color12=#58C1FE
color13=#FEED98
color14=#94E5CA
color15=#FEFEFE
EOF
        ;;
    "Elementary")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/elementary.colors

# elementary.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#303030
color1=#e1321a
color2=#6ab017
color3=#ffc005
color4=#004f9e
color5=#ec0048
color6=#2aa7e7
color7=#f2f2f2
color8=#5d5d5d
color9=#ff361e
color10=#7bc91f
color11=#ffd00a
color12=#0071ff
color13=#ff1d62
color14=#4bb8fd
color15=#a020f0
background=#101010
foreground=#f2f2f2
cursor=#f2f2f2
EOF
        ;;
    "Everblush")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/everblush.colors

foreground=#dadada
background=#141b1e
cursor=#3b4244

# normal colors
color0=#232a2d
color1=#e57474
color2=#8ccf7e
color3=#e5c76b
color4=#67b0e8
color5=#c47fd5
color6=#6cbfbf
color7=#b3b9b8

# bright colors
color8=#2d3437
color9=#ef7e7e
color10=#96d988
color11=#f4d67a
color12=#71baf2
color13=#ce89df
color14=#67cbe7
color15=#bdc3c2
EOF
        ;;
    "Flat")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/flat.colors

# flat.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#2c3e50
color1=#c0392b
color2=#27ae60
color3=#f39c12
color4=#2980b9
color5=#8e44ad
color6=#16a085
color7=#bdc3c7
color8=#34495e
color9=#e74c3c
color10=#2ecc71
color11=#f1c40f
color12=#3498db
color13=#9b59b6
color14=#2AA198
color15=#ecf0f1
background=#1F2D3A
foreground=#1abc9c
cursor=#1abc9c
EOF
        ;;
    "Material Ocean")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/material-ocean.colors

# material.ocean.colors
# Color scheme from https://github.com/Material-Ocean
color0  = #3b4252
color1  = #bf616a
color2  = #a3be8c
color3  = #ebcb8b
color4  = #81a1c1
color5  = #b48ead
color6  = #88c0d0
color7  = #e5e9f0
color8  = #4c566a
color9  = #bf616a
color10 = #a3be8c
color11 = #ebcb8b
color12 = #81a1c1
color13 = #b48ead
color14 = #8fbcbb
color15 = #eceff4
background=#0f111a
foreground=#d8dee9
cursor=#d8dee9
EOF
        ;;
    "Material")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/material.colors

# material.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#073641
color1=#EB606B
color2=#C3E88D
color3=#F7EB95
color4=#80CBC3
color5=#FF2490
color6=#AEDDFF
color7=#FFFFFF
color8=#002B36
color9=#EB606B
color10=#C3E88D
color11=#F7EB95
color12=#7DC6BF
color13=#6C71C3
color14=#34434D
color15=#FFFFFF
background=#1E282C
foreground=#C3C7D1
cursor=#657B83
EOF
        ;;
    "Monokai Dark")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/monokai-dark.colors

# monokai.dark.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#75715e
color1=#f92672
color2=#a6e22e
color3=#f4bf75
color4=#66d9ef
color5=#ae81ff
color6=#2AA198
color7=#f9f8f5
color8=#272822
color9=#f92672
color10=#a6e22e
color11=#f4bf75
color12=#66d9ef
color13=#ae81ff
color14=#2AA198
color15=#f8f8f2
background=#272822
foreground=#f8f8f2
cursor=#f8f8f2
EOF
        ;;
    "Nekonako Djancoeg")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/nekonako-djancoeg.colors

color0=#2f343f
color1=#fd6b85
color2=#63e0be
color3=#fed270
color4=#67d4f2
color5=#ff8167
color6=#63e0be
color7=#eeeeee
color8=#4f4f5b
color9=#fd6b85
color10=#63e0be
color11=#fed270
color12=#67d4f2
color13=#ff8167
color14=#63e0be
color15=#eeeeee
background=#2a2c3a
#background=#090d13
foreground=#eeeeee
cursor=#fd6b85
EOF
        ;;
    "Nekonako Hue")
        cat >"$COLORS_FILE" <<'EOF'
#  https://github.com/mayTermux/myTermux/blob/main/.colorscheme/nekonako-hue.colors

color0=#291e4e
color1=#fb749f
color2=#86d387
color3=#fbdd74
color4=#8e96fd
color5=#d685ff
color6=#9bcfcf
color7=#ffffff
color8=#291e4e
color9=#fb749f
color10=#86d387
color11=#fbdd74
color12=#8e96fd
color13=#d685ff
color14=#9bcfcf
color15=#ffffff
background=#291e4e
foreground=#ffffff
cursor=#fb749f
EOF
        ;;
    "Nekonako Om Mar")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/nekonako-om-mar.colors

! Color scheme by fikri omar

background=#2F343F
foreground=#EFF0EB

color0=#2F343F
color8=#444A57

color1=#de8990
color9=#d0a8ab

color2=#94daa9
color10=#bae8d2

! yellow
color3=#dee7aa
color11=#d7c96b

! blue
color4=#9cdbdf
color12=#6cb4dd

! magenta
color5=#cca8c9
color13=#db79bf

! cyan
color6=#9ad4c8
color14=#59b0b2

! white
color7=#e1e1e1
color15=#f0f0f0
EOF
        ;;
    "Owl4ce Dark")
        cat >"$COLORS_FILE" <<'EOF'
#  https://github.com/mayTermux/myTermux/blob/main/.colorscheme/owl4ce-dark.colors

color0=#434C5E
color1=#FA5AA4
color2=#2BE491
color3=#FA946E
color4=#63C5EA
color5=#CF8EF4
color6=#89CCF7
color7=#F7F7F7
color8=#4C566A
color9=#FA74B2
color10=#44EB9F
color11=#FAA687
color12=#7ACBEA
color13=#D8A6F4
color14=#A1D5F7
color15=#F4F4F4
background=#373E4D
foreground=#F9F9F9
cursor=#FA5AA4
EOF
        ;;
    "Siduck Onedark")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/siduck-onedark.colors

foreground=#c8ccd4
background=#1e222a
cursor=#e06c75
color0=#1e222a
color1=#e06c75
color2=#98c379
color3=#e5c07b
color4=#61afef
color5=#c678dd
color6=#56b6c2
#color7=#abb2bf
color7=#D8DEE9
color8=#545862
color9=#e06c75
color10=#98c379
color11=#e5c07b
color12=#61afef
color13=#c678dd
color14=#56b6c2
color15=#c8ccd4
EOF
        ;;
    "Snazzy")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/snazzy.colors

# snazzy.colors
# Color theme from Color scheme from https://github.com/Mayccoll/Gogh
color0=#0C0D13
color1=#FF5C57
color2=#5AF78E
color3=#F3F99D
color4=#57C7FF
color5=#FF6AC1
color6=#9AEDFE
color7=#EFF0EB
color8=#686868
color9=#FF5C57
color10=#5AF78E
color11=#F3F99D
color12=#57C7FF
color13=#FF6AC1
color14=#9AEDFE
color15=#EFF0EB
background=#282A36
foreground=#EFF0EB
cursor=#EFF0EB
EOF
        ;;
    "Tomorrow Night")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/tomorrow-night.colors

# tomorrow.night.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#000000
color1=#CC6666
color2=#B5BD68
color3=#F0C674
color4=#81A2BE
color5=#B293BB
color6=#8ABEB7
color7=#FFFEFE
color8=#000000
color9=#CC6666
color10=#B5BD68
color11=#F0C574
color12=#80A1BD
color13=#B294BA
color14=#8ABDB6
color15=#FFFEFE
background=#1D1F21
foreground=#C5C8C6
cursor=#C4C8C5
EOF
        ;;
    "Tomorrow Night Eighties")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/tomorrow-night.eighties.colors

# tomorrow.night.eighties.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#000000
color1=#F27779
color2=#99CC99
color3=#FFCC66
color4=#6699CC
color5=#CC99CC
color6=#66CCCC
color7=#FFFEFE
color8=#000000
color9=#F17779
color10=#99CC99
color11=#FFCC66
color12=#6699CC
color13=#CC99CC
color14=#66CCCC
color15=#FFFEFE
background=#2C2C2C
foreground=#CCCCCC
cursor=#CCCCCC
EOF
        ;;
    "Xshin")
        cat >"$COLORS_FILE" <<'EOF'
# https://github.com/mayTermux/myTermux/blob/main/.colorscheme/xshin.colors

# custom.colors
color0=#44475a
color1=#ff0000
color2=#00ff00
color3=#ff8e1e
color4=#0071ff
color5=#ffc500
color6=#808080
color7=#ffffff
color8=#000000
color9=#ff0000
color10=#50fa7b
color11=#ff8e1e
color12=#0071ff
color13=#ffc500
color14=#808080
color15=#ffffff
background=#282a36
foreground=#ffffff
cursor=#94A3A5
EOF
        ;;

    esac

    termux-reload-settings
}

# Get all available schemes
get_schemes() {
    echo "Catppuccin Macchiato"
    echo "Catppuccin Mocha"
    echo "Catppuccin Latte"
    echo "Catppuccin Frappe"
    echo "Dracula"
    echo "Gruvbox Dark"
    echo "Nord"
    echo "One Dark"
    echo "Solarized Dark"
    echo "Tokyo Night"
    echo "Monokai"
    echo "Oceanic Next"
    echo "Ubuntu"
    echo "E-link Color"
    echo "E-link"
    echo "Ayu Dark"
    echo "Ayu Light"
    echo "Ayu Mirage"
    echo "Elementary"
    echo "Everblush"
    echo "Flat"
    echo "Material Ocean"
    echo "Material"
    echo "Monokai Dark"
    echo "Nekonako Djancoeg"
    echo "Nekonako Hue"
    echo "Nekonako Om Mar"
    echo "Owl4ce Dark"
    echo "Siduck Onedark"
    echo "Snazzy"
    echo "Tomorrow Night"
    echo "Tomorrow Night Eighties"
    echo "Xshin"
}

# Main TUI function
show_menu() {
    local search_term=""
    local selected=0
    local schemes=()

    while IFS= read -r scheme; do
        schemes+=("$scheme")
    done < <(get_schemes)

    while true; do
        clear

        # Filter schemes based on search term
        local filtered_schemes=()
        local i=0
        for scheme in "${schemes[@]}"; do
            if [[ -z "$search_term" ]] || [[ "${scheme,,}" == *"${search_term,,}"* ]]; then
                filtered_schemes+=("$scheme")
            fi
        done

        # Adjust selected index if needed
        if ((selected >= ${#filtered_schemes[@]})); then
            selected=$((${#filtered_schemes[@]} - 1))
        fi
        if ((selected < 0)); then
            selected=0
        fi

        # Header
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "          TERMUX COLOR SWITCHER  "
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "Use ↑↓ to navigate, type to search, ENTER to select, ESC to exit"
        echo ""

        # Show filtered schemes
        for i in "${!filtered_schemes[@]}"; do
            if ((i == selected)); then
                echo "→ ${filtered_schemes[i]}"
            else
                echo "  ${filtered_schemes[i]}"
            fi
        done

        # Show current preview
        if ((${#filtered_schemes[@]} > 0)); then
            echo ""
            echo "Preview: ${filtered_schemes[selected]}"
            echo ""
            echo -n "Search: $search_term"
            apply_colors "${filtered_schemes[selected]}"
        fi

        # Read input
        IFS= read -rsn1 key
        case "$key" in
        $'\033') # ESC key - first check if it's a standalone ESC
            # Try to read additional characters with a short timeout
            read -rsn2 -t 0.1 key2
            if [[ -z "$key2" ]]; then
                # It's a standalone ESC key
                clear
                restore_colors
                exit 0
            else
                case "$key2" in
                '[A') # Up arrow
                    ((selected--))
                    if ((selected < 0)); then
                        selected=$((${#filtered_schemes[@]} - 1))
                    fi
                    ;;
                '[B') # Down arrow
                    ((selected++))
                    if ((selected >= ${#filtered_schemes[@]})); then
                        selected=0
                    fi
                    ;;
                esac
            fi
            ;;
        '') # Enter
            if ((${#filtered_schemes[@]} > 0)); then
                clear
                echo "[✓] Color scheme '${filtered_schemes[selected]}' has been applied!"
                rm -f "$BACKUP_FILE" 2>/dev/null
                exit 0
            fi
            ;;
        $'\x7f' | $'\x08') # Backspace
            if [[ -n "$search_term" ]]; then
                search_term="${search_term%?}"
                selected=0
            fi
            ;;
        *)
            if [[ -n "$key" && "$key" =~ [[:print:]] ]]; then
                search_term+="$key"
                selected=0
            fi
            ;;
        esac
    done
}

# Main execution
main() {
    # Check if running in Termux
    if [[ -z "$PREFIX" && "$PREFIX" != *"/com.termux/"* ]]; then
        echo "[☓] Please run it inside termux"
        exit 0
    fi

    # Create .termux directory if it doesn't exist
    if [[ ! -d "$HOME/.termux" ]]; then
        mkdir -p "$HOME/.termux"
    fi

    # Backup current colors
    backup_colors

    # Set up trap to restore colors on script exit
    trap restore_colors INT TERM

    # Show the menu
    show_menu
}

# Run the script
main "$@"
