#!/data/data/com.termux/files/usr/bin/bash

function hw_install_required_packages() {
    banner
    echo "${R} [${W}-${R}]${G}${BOLD}Installing Required Packages For Hardware Acceleration"${W}
	echo
    pacman -Rdd vulkan-loader
    if [[ "$termux_hw_answer" == "1" ]]; then
    #zink
    hw_package_list="mesa-zink vulkan-loader-android angle-android virglrenderer"
    elif [[ "$termux_hw_answer" == "2" ]]; then
    #virgl angle
    hw_package_list="angle-android virglrenderer-android"
    elif [[ "$termux_hw_answer" == "3" ]]; then
    #virgl zink
    hw_package_list="mesa-zink virglrenderer-mesa-zink vulkan-loader-android angle-android virglrenderer-android"
    elif [[ "$termux_hw_answer" == "4" ]]; then
    #freedreno
    hw_package_list="mesa-zink mesa-zink-vulkan-icd-freedreno mesa-vulkan-icd-freedreno-dri3"
    fi
    if type -p pacman >/dev/null 2>&1; then
    package_check_and_remove "mesa vulkan-loader"
    fi
    package_install_and_check "${hw_package_list}"
}

#########################################################################
#
# Add HW Server Initialize Method
#
#########################################################################

function setup_hw_method() {
   if [[ $termux_hw_answer == "1" ]]; then
    initialize_server_method="MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 GALLIUM_DRIVER=zink ZINK_DESCRIPTORS=lazy virgl_test_server --use-egl-surfaceless --use-gles"
    hw_method="GALLIUM_DRIVER=zink MESA_GL_VERSION_OVERRIDE=4.0"
    pd_hw_method="GALLIUM_DRIVER=zink MESA_GL_VERSION_OVERRIDE=4.0"
elif [[ $termux_hw_answer == "2" ]]; then
    initialize_server_method="virgl_test_server_android --angle-gl"
    hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
    pd_hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
elif [[ $termux_hw_answer == "3" ]]; then
    initialize_server_method="MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 GALLIUM_DRIVER=zink ZINK_DESCRIPTORS=lazy virgl_test_server --use-egl-surfaceless --use-gles"
    hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
    pd_hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
elif [[ $termux_hw_answer == "4" ]]; then
    initialize_server_method=" "
    hw_method="MESA_LOADER_DRIVER_OVERRIDE=zink"
    pd_hw_method="MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform"
else
    initialize_server_method="MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 GALLIUM_DRIVER=zink ZINK_DESCRIPTORS=lazy virgl_test_server --use-egl-surfaceless --use-gles"
    hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
fi
if [[ "$termux_hw_answer" == "2" ]]; then
    if [[ $pd_hw_answer == "1" ]]; then
    pd_hw_method="GALLIUM_DRIVER=zink MESA_GL_VERSION_OVERRIDE=4.0"
    elif [[ $pd_hw_answer == "2" ]]; then
    pd_hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
    elif [[ $pd_hw_answer == "3" ]]; then
    pd_hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
    elif [[ $pd_hw_answer == "4" ]]; then
    pd_hw_method="MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform"
    else
    echo "${R}[${W}-${R}]${G}Uses The Previous Selection For Distro"${W}
    echo
    fi
else
    if [[ $pd_hw_answer == "1" ]]; then
    pd_hw_method="GALLIUM_DRIVER=zink MESA_GL_VERSION_OVERRIDE=4.0"
    elif [[ $pd_hw_answer == "2" ]]; then
    pd_hw_method="GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.0"
    elif [[ $pd_hw_answer == "3" ]]; then
    pd_hw_method="MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform"
    else
    echo "${R}[${W}-${R}]${G}Uses The Previous Selection For Distro"${W}
    echo
    fi
fi
}

hw_install_required_packages
setup_hw_method